# Site settings
title: Christian Wookey
description: Resume of Christian Wookey
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Christian Wookey
user_description: I'm a Game Designer and Programmer about to finish my BS in Game Design & Computer Science at DigiPen Institute of Technology. My primary skills are gameplay design, level design, and AI programming.
user_title: Game Designer & Programmer
email: christian.wookey@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: cwookey
github_username: cwook
itch_username: cwook
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

